
dfSTATEHOUSINGTOTALS<-left_join(dfSTATETOTALS, dfSTATEHOUSING, by = "STATE")
dfSTATEHOUSINGTOTALS<-transform(dfSTATEHOUSINGTOTALS, NUM_ESTABLISHMENTS = as.numeric(as.character(NUM_ESTABLISHMENTS)))
dfSTATEHOUSINGTOTALS<-transform(dfSTATEHOUSINGTOTALS, NUM_FIRMS = as.numeric(as.character(NUM_FIRMS)))
dfSTATEHOUSINGTOTALS<-transform(dfSTATEHOUSINGTOTALS, PAYROLL = as.numeric(as.character(PAYROLL)))
dfSTATEHOUSINGTOTALS<-transform(dfSTATEHOUSINGTOTALS, EMPLOYMENT = as.numeric(as.character(EMPLOYMENT)))
dfSTATEHOUSINGTOTALS2 <- dfSTATEHOUSINGTOTALS%>%select(STATE,NUM_FIRMS, NUM_ESTABLISHMENTS,EMPLOYMENT, POPULATION, POPULATIONDENSITY)%>%filter(NUM_FIRMS>100000)
dfSTATEHOUSINGTOTALS3<-dfSTATEHOUSINGTOTALS%>%select(STATE,NUM_FIRMS, NUM_ESTABLISHMENTS,EMPLOYMENT, POPULATION, POPULATIONDENSITY)%>%mutate(EMPLOYMENT_RATE=EMPLOYMENT/POPULATION)

