dfSTATEHOUSINGTOTALS<-left_join(dfSTATETOTALS, dfSTATEHOUSING, by = "STATE")
dfSTATEHOUSINGTOTALS<- dfSTATEHOUSINGTOTALS %>% mutate(EMP_RATE=EMPLOYMENT/POPULATION) %>% mutate(WATER_PERC=WATERAREA/TOTALAREA) %>% mutate(LAND_PERC=LANDAREA/TOTALAREA) %>% mutate(AVG_EMP=EMPLOYMENT/NUM_ESTABLISHMENTS) %>% mutate(AVG_PAY=PAYROLL/POPULATION)
dfSTATECOMPGROWTH <- dfTOPCOMPANIES %>% group_by(STATE) %>% summarise (groAvg = mean(GROWTH), revAvg = mean(REVENUE))
dfTOTALS<- left_join(dfSTATEHOUSINGTOTALS, dfSTATECOMPGROWTH, by="STATE")
dfNormalized <- dfTOTALS %>% mutate(VarianceEMP_RATE=(EMP_RATE-mean(EMP_RATE))) %>% mutate(VarianceAVG_EMP=(AVG_EMP-mean(AVG_EMP))) %>% mutate(VarianceAVG_PAY=(AVG_PAY-mean(AVG_PAY))) %>% mutate(VarianceGro_Avg=(groAvg-mean(groAvg))) %>% mutate(VarianceRevAvg=(revAvg-mean(revAvg)))
dfNormalized <- dfNormalized %>% select(VarianceAVG_EMP, VarianceAVG_PAY, VarianceGro_Avg)
